import scala.io.Source

case class AEFIRecord(
                     date: String,
                     vaxtype: String,
                     daily_total: Int,
                     daily_serious_npra: Int,
                     daily_nonserious: Int,
                     daily_nonserious_npra: Int,
                     daily_nonserious_mysj_dose1: Int,
                     daily_nonserious_mysj_dose2: Int,
                     d1_site_pain: Int,
                     d1_site_swelling: Int,
                     d1_site_redness: Int,
                     d1_tiredness: Int,
                     d1_headache: Int,
                     d1_muscle_pain: Int,
                     d1_joint_pain: Int,
                     d1_weakness: Int,
                     d1_fever: Int,
                     d1_vomiting: Int,
                     d1_chills: Int,
                     d1_rash: Int,
                     d2_site_pain: Int,
                     d2_site_swelling: Int,
                     d2_site_redness: Int,
                     d2_tiredness: Int,
                     d2_headache: Int,
                     d2_muscle_pain: Int,
                     d2_joint_pain: Int,
                     d2_weakness: Int,
                     d2_fever: Int,
                     d2_vomiting: Int,
                     d2_chills: Int,
                     d2_rash: Int,
                     )